### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by TheZoker** [Awesome-Support/Awesome-Support#136]
I got some issues in the debug log:
<pre>PHP Notice:  Trying to get property of non-object in /wp-content/plugins/awesome-support-notifications/class-notify.php on line 139
PHP Notice:  Trying to get property of non-object in /wp-content/plugins/awesome-support/includes/functions-templating.php on line 41
PHP Notice:  Trying to get property of non-object in /wp-content/plugins/awesome-support/includes/functions-general.php on line 269
PHP Notice:  Undefined variable: post_id in /wp-content/plugins/awesome-support-notifications/class-notifications.php on line 134
array_key_exists(): The first argument should be either a string or an integer in /wp-content/plugins/awesome-support/includes/addons/custom-fields/class-custom-fields.php on line 454</pre>

**Comment by SiamKreative** [comment]
I'm unable to replicate the issue.

If you're still seeing these notices, please re-open this issue and please explain me how to replicate the issue.
