### ISSUE TITLE
Add Link to Products

### ISSUE THREAD

**Issue by julien731** [Awesome-Support/Awesome-Support#159]
When multi-product is enabled, it can be useful to let users add a link to the product (for instance link to a product page).

This however, should be automated if an e-commerce integration is enabled.

**Comment by julien731** [comment]
All things considered, this makes sense with an e-commerce plugin active, but I don't really see what would be the use case otherwise.

**Comment by SiamKreative** [comment]
Also, having a link to the product page only on the ticket list is not the most useful. It could be more useful when a user submits a new ticket... (but it's a select dropdown)
