### ISSUE TITLE
Ability to add new "Ticket creator" from the dropdown

### ISSUE THREAD

**Issue by SiamKreative** [Awesome-Support/Awesome-Support#191]
We should add the ability to create a new support user from the metabox Stakeholders... In the dropdown:
1. Add "A new user"
2. Triggers a Thickbox Modal
3. Inside we have a form for user creation

That's it. Is it really needed? Perhaps no, but in case someone create new tickets on behalf of clients it could become useful.

**Comment by elindydotcom** [comment]
This is now part of our POWERPACK (Productivity) add-on so closing this issue.
