### ISSUE TITLE
Switch from Grunt to Gulp

### ISSUE THREAD

**Issue by SiamKreative** [Awesome-Support/Awesome-Support#192]
* https://medium.com/@preslavrachev/gulp-vs-grunt-why-one-why-the-other-f5d3b398edc4
* http://sixrevisions.com/web-development/grunt-vs-gulp/

![image](https://cloud.githubusercontent.com/assets/1778633/9849831/b4987eb6-5b18-11e5-9874-d45571e794ce.png)

Because Gulp is faster and I like it more and more...

**Comment by tripflex** [comment]
With the basic tasks that are used right now I don't see the real benefit unless maybe you're using watch constantly, but even then depending on your workflow by the time you go to browser grunt would be done as well.

I've been following gulp for a while, and it looks very promising as soon I will probably start using it in new projects, but at this time Grunt is still more widely used, meaning more packages, online discussions, etc, and with only using it for concat, uglify, watch, and translation stuff ... 

Now I could be completely wrong as I do not know your workflow, but just figured I would give my opinion as I have been in a few discussions with different devs about this and everyone has their own feelings towards it :+1:   

Either way what you decide on i'll support :P

**Comment by SiamKreative** [comment]
Thanks for sharing your opinion. I agree on everything... it's probably not worth the trouble it right now, especially as some Grunt plugins that we use haven't been ported to Gulp yet. I'm closing this for now.
