### ISSUE TITLE
File Upload Admin Live Validation

### ISSUE THREAD

**Issue by julien731** [Awesome-Support/Awesome-Support#193]
Live validation has been added on the front-end but it'd be useful to have it in the back-end also (for agents).

In order to keep it clean, that would require breaking down the publis JS file into smaller, feature-oriented files that would be automatically concatenated into `public.js` by a Grunt task.

**Comment by SiamKreative** [comment]
It's pretty easy now that JS is already split by components. We need to:
- [ ] Enqueue `assets/public/js/helpers_functions.js`
- [ ] Enqueue `assets/public/js/component_upload.js`
- [ ] Have the JavaScript object `wpas` accessible from the Dashboard as well (the one that includes parameters, etc)
