### ISSUE TITLE
Custom Fields Field Types

### ISSUE THREAD

**Issue by julien731** [Awesome-Support/Awesome-Support#196]
This issue is used as a summary for the custom fields field types available and planned. If you wish to see new field types, please check the **Coming Soon** and **Requested** sections first. If your field type is not in the list, you can request it in the comments.

I will try to keep the list up to date so that everyone can have a quick overview of what's to come.
# Built-In
- Checkbox
- Date
- Email
- Number
- Password
- Radio
- Select
- Taxonomy
- Text
- Textarea
- Upload
- URL
- WYSIWYG
# Coming Soon
- None yet *
# Requested
- Colorpicker
- [Posts select](https://github.com/Awesome-Support/Awesome-Support/issues/196#issuecomment-181672553)

**Comment by alpha1** [comment]
I'd like to request a select field, similar to taxonomies, but for posts. Pick a post type(s) and show all posts that fit the criteria.

**Comment by nachumie** [comment]
Dear @julien731 , 
I'd like to use the date field (date-picker?), however using the following code will not present the date-picker;
`	wpas_add_custom_field( 'purchase_date', 
		array(
			'title' => __( 'Date of Purchase', 'wpas' ),
			'field_type' => 'date'
			)
		);`
Anything i'm doing wrong?

**Comment by julien731** [comment]
Hey @nachumie , you should be using `'field_type' => 'date-field'`. A bit confusing maybe but this is because using just `date` conflicts with PHP's `date()` function.

**Comment by mbtocalli** [comment]
`'required' => false` doesn't seems to work

**Comment by waleedt93** [comment]
Hi @alpha1 
Is there any update upon your request? As i need the same thing which you want? if yes please let me know.
Thanks

**Comment by alpha1** [comment]
@waleedt93 Nope, sorry.

**Comment by talyash** [comment]
Would it be possible to add a type="hidden" input? For when I want to use JS to set the value, but still have it show up everywhere else.

**Comment by hzqabdullah** [comment]
hello, i have a problem. we should i put `wpas_add_custom_field( 'my_custom_field',  array( 'title' => __( 'My Custom Field', 'wpas' ), 'order' => 1 ) );`. In awesome support documentation says that i should put it in /wp-content/plugins/awesome-support-custom-fields.php file but i only had awesome-support.php. Can you please help me?

**Comment by sheinavi** [comment]
Hi! I did the custom fields plugin, however, I need multiple forms with different fields. I have a URL parameter,for example, `&form_number=10` , it should show only specific fields. So I have this in the plugin
 
`$form_number = $_GET['form_number']` 

then had 

if($form_number == '10') 
   _show only these fields_

I also have few common fields outside the IFs. It worked in front end but in the admin side it only shows the common fields..

Do you guys have any other way to do this?

**Comment by nahasco** [comment]
I am trying to add a simple text custom field titled as order number where the user inputs his order number. My knowledge in html and php is 0 so I hope I would get some help here.

**Comment by jackcoral89** [comment]
For a create a select custom field i used the following code but not work, not show anything on frontend:
`        wpas_add_custom_field('campo_custom_3',  array(
            'title' => __('Campo custom 3', 'awesome-support'),
            'field_type' => 'select',
            'required' => true
        ));`

**Comment by jackcoral89** [comment]
Resolved `'field_type' => 'select'` options:
`        wpas_add_custom_field('my_field_with_options', array(
            'title' => 'My Options',
            'field_type' => 'select',
            'options' => array(
                'option1' => 'First Option',
                'option2' => 'Second Option'
            ),
            'order' => 1
        ));
`

**Comment by jackcoral89** [comment]
How disabled default filed ? like wysiwyg
![image](https://user-images.githubusercontent.com/27479143/69638176-7c7eb080-105a-11ea-811b-058fc1f7ed60.png)

**Comment by jackcoral89** [comment]
I need of premium support for above issue? @julien731

**Comment by jackcoral89** [comment]
Resolved also this! thx for "awesome support" 🙃

**Comment by lanre-s** [comment]
Hey @jackcoral89 How did you 

> How disabled or hide default field without using css ? like wysiwyg ![image](https://user-images.githubusercontent.com/27479143/69638176-7c7eb080-105a-11ea-811b-058fc1f7ed60.png)

How did you resolve this?

**Comment by avdegt1976** [comment]
Your documentation is completely wrong
(typically /wp-content/plugins/awesome-support-custom-fields.php
^^^ if I do so, no fields added at all

If I add my code wpas_add_custom_field( $name, $args ) and all of this bla bla bla to the functions.php -it works

Is it possible to create working manual, not the one you have created???

**Comment by avdegt1976** [comment]
I am working on create a very simple solution for company partners
Each partner should maintain an easy table like name, tel, email and that's all

I don't need anything like "Goods" or HTML-styled comment and so on
Can  I remove all these fields that I do not really need?

I realized it is not easy to add custom fields in this, however to remove the one is not easy as well

**Comment by avdegt1976** [comment]
project is dead, I guess...

**Comment by yeisonbp** [comment]
> 

@avdegt1976, the project is not dead, I apologize for not replying. We usually offer assistance in the WordPress forum. Now:

1- You can deactivate the priority, products and department fields by going to tickets - settings - fields tab. 
2- You cannot hide the description field as it is needed for submitting tickets, but you can set default content on those fields using the Productivity add-on: https://getawesomesupport.com/documentation/productivity/set-default-content-subject-description-field-front-end/ and https://getawesomesupport.com/addons/productivity/
3- For adding custom fields without code, we have the Custom Fields add-on: https://getawesomesupport.com/addons/custom-fields/
4- For free custom fields code, we only have this documentation: - https://getawesomesupport.com/documentation/awesome-support/custom-fields/

Any questions, let me know :)

**Comment by elindydotcom** [comment]
@yeisonbp , I do believe this issue should be closed.

The GITHUB project is a development forum, not a technical support forum.  No one should be expecting or demanding technical support on here.  avdegt1976's expectations for free support on here is completely out of line and you should not have felt the need to respond to it.  Your company already has multiple avenues that offer technical support for this project and those should have been used for that request.
