### ISSUE TITLE
No product counts, and no filtering by product

### ISSUE THREAD

**Issue by tivnet** [Awesome-Support/Awesome-Support#213]
@julien731 Tried to debug this today, with no luck.

"Multiple Product" set.
Product name is visible, but counters are always zero, and when clicking on product name, always get empty list.

![wpas-no-product-counts](https://cloud.githubusercontent.com/assets/1696330/9974595/6ce91a6c-5e65-11e5-99a8-40481a1f5e09.png)

**Comment by julien731** [comment]
Yeah that's a bug that only happens with products synced with an e-commerce plugin. The reason is this: https://github.com/ThemeAvenue/Awesome-Support/blob/master/includes/class-product-sync.php#L29

I wasn't able to find a solution for now :(

**Comment by tivnet** [comment]
@julien731 OK, pity, but can live with that for now.

One more thing:

```
if ( 'taxonomy' !== $taxonomy['args']['callback'] ) {
			continue;
		}
```

gives me notices because there is no `'callback'`. Is this piece of code valid? 

(at least, there should be `isset`)

Merci

**Comment by julien731** [comment]
@tivnet , the `callback` parameter has been deprecated and replaced by `field_type` for all custom fields.
