### ISSUE TITLE
WooCommerce users cannot submit tickets

### ISSUE THREAD

**Issue by tivnet** [Awesome-Support/Awesome-Support#217]
@julien731 

After the 20b03f31e8511653d7733eedfba4a1c5e5e2e7d5 commit, WC users cannot submit tickets.

They are registering on WooCommerce's "My Account" login/register page, receive the role "Customer", which is below the Support User, and so does not have the `create_ticket` capability.

**Comment by tivnet** [comment]
... and you just return `false`, having the filter later, so it does not even come to the filter.

**Comment by tivnet** [comment]
I was able to change the WC default user's role to 'wpas_user', but such commits really break the WPAS functionality. :-1:

**Comment by tivnet** [comment]
... Oh, no. All existing WC users, even customers, subscribers cannot submit tickets...

That's too bad.

:-1: :-1: :-1: :-1:

**Comment by SiamKreative** [comment]
I'll test this today.

**Comment by SiamKreative** [comment]
To let WooCommerce users submit tickets **without the WooCommerce addon**, please read this FAQ: [Users get “You do not have the capacity to open a new ticket”](https://getawesomesupport.com/question/users-get-you-do-not-have-the-capacity-to-open-a-new-ticket/)
