### ISSUE TITLE
Notice if no $agent

### ISSUE THREAD

**Issue by tivnet** [Awesome-Support/Awesome-Support#218]
```
$agent  = get_user_by( 'id', intval( get_post_meta( $this->ticket_id, '_wpas_assignee', true )
```

Need to check if there was no meta, and do something to prevent notice when trying to use the `$agent` object.

I had this when none of the users had "auto assign", so new tickets did not have any agents, and email notifications were broken. (And also notices in the list of tickets in admin)

**Comment by julien731** [comment]
Where is that exactly?

**Comment by tivnet** [comment]
https://github.com/Awesome-Support/Awesome-Support/blob/master/includes/class-email-notifications.php#L357
