### ISSUE TITLE
Auto-linking is not working properly

### ISSUE THREAD

**Issue by SiamKreative** [Awesome-Support/Awesome-Support#225]
See test ticket: https://getawesomesupport.com/wp-admin/post.php?post=64198&action=edit

![image](https://cloud.githubusercontent.com/assets/1778633/10037204/f7883124-61dc-11e5-9aae-d06df572c98f.png)

There are quite a few cases where it doesn't work. Also, if editing a reply, the auto-linking won't work at all (need to reload the page to see the auto-linking in action). Using a [javascript library](http://stackoverflow.com/a/21925491) should solve both issue...

**Comment by SiamKreative** [comment]
For instance, this is what **Autolinker.js** does:

- Autolinks URLs, whether or not they start with the protocol (i.e. 'http://').
  In other words, it will automatically link the text "google.com", as well as
  "http://google.com".
- Will properly handle URLs with special characters
- Will properly handle URLs with query parameters or a named anchor (i.e. hash)
- Will autolink email addresses.
- Will autolink phone numbers.
- Will autolink Twitter handles.
- Will autolink hashtags.
- Will properly handle HTML input. The utility will not change the `href`
  attribute inside anchor (&lt;a&gt;) tags (or any other tag/attribute for that
  matter), and will not accidentally wrap the inner text of an anchor tag with a
  new one (which would cause doubly-nested anchor tags).

**Comment by julien731** [comment]
:+1:

**Comment by julien731** [comment]
Let's add Autolinker.js @SiamKreative
