### ISSUE TITLE
Adding count bubble and using icon?

### ISSUE THREAD

**Issue by tripflex** [Awesome-Support/Awesome-Support#234]
Wondering what you guys thoughts are on this as I couldn't find anything in issue search, and figured I would ask.

With my experience in using support tickets through WordPress, I've found that having the count bubble next to the menu item is very helpful when agents are on the site's admin section, but may not know at the time that a new ticket was submitted, unless they check their emails.

![](https://smyl.es/img/Screenshot_2015-10-07_12-16-39_PM.png)

Having the count bubble show would eliminate the need to monitor your email or the ticket list page to see when there is an active ticket awaiting a reply ... what do you guys think?

Also, what about using the icon instead of **My Tickets** in the admin header bar?  I think that would make it look less cluttered, plus could also add the ticket count there as well (to show when admin is browsing site and does not see main menu)?

![](https://smyl.es/img/Screenshot_2015-10-07_12-21-59_PM.png)

Maybe even use the tickets dashicon:

![](https://smyl.es/img/Screenshot_2015-10-07_12-22-37_PM.png)

This could be handled a number of different ways, including using the `add_menu_classes` hook and adding the **count-**XXX class to our specific menu item

**Comment by tripflex** [comment]
Well now I take back the bubble question, as it seems it already exists ... not sure why it wasn't showing when I had an open ticket (did refresh the page), but it is showing now so I guess that's a feature that already exists :+1:

**Comment by SiamKreative** [comment]
Thanks @tripflex 

I made some changes on a branch. I tried to be as close as possible to the WordPress UI (the way updates are displayed, for instance).

* Replace My Tickets with ticket count & Add icon (c503d5e4dfd907fa99f5058b850a96dbe52dca99)

**Comment by julien731** [comment]
84afed36fef1ad6f9321f5015718b08115b8190f merged into core.

**Comment by SiamKreative** [comment]
The CSS related to this is not loaded on every pages. It should be. @julien731
