### ISSUE TITLE
You can't submit an empty reply JS admin error

### ISSUE THREAD

**Issue by tripflex** [Awesome-Support/Awesome-Support#235]
This commit:
https://github.com/Awesome-Support/Awesome-Support/commit/680e9344b8c7d4dda1b92d7640ff5616de5d9707

Causes a JS error and essentially prevents anybody from submitting a reply in admin section when using **Visual** ... only works on textarea

https://github.com/Awesome-Support/Awesome-Support/blob/master/assets/admin/js/admin.js#L73

That's because it looks like you're referencing the `editor` var which has not been set, and should be checking `tinyMCE.activeEditor`

**Comment by SiamKreative** [comment]
Thanks for doing this man, I really appreciate it!
