### ISSUE TITLE
Load "awesome-support" text domain instead of "wpas"

### ISSUE THREAD

**Issue by nash-ye** [Awesome-Support/Awesome-Support#243]
Thank you before all, for developing this great plugin. I am working to use it in my personal site, but I had found some bugs that needs to be fixed ASAP.

Currently most plugin translatable strings associated with "awesome-support" text domain, where as "wpas" is used in only 8 strings!

Clearly, "awesome-support" text domain must be loaded instead of "wpas" by load_textdomain() and load_plugin_textdomain() functions.

**Comment by julien731** [comment]
Indeed this is a bug that you spotted. However, it was fixed in the development version (see a4b76f9390aab0aad7592b60f05b5348ebdde1c1 and 9896e7f406eae3d79d42258beb6e3c6575834776). We will release and update to the core soon that will fix that.

**Comment by nash-ye** [comment]
Thank you. :+1:
