### ISSUE TITLE
Add visible link "Lost Your Password"

### ISSUE THREAD

**Issue by SiamKreative** [Awesome-Support/Awesome-Support#247]
> The "lost password" link appears in the error message in case of an incorrect login, but I agree it could be easier to have the link in the form if you forgot your password upfront.

https://wordpress.org/support/topic/feature-request-lost-your-password-link?replies=2

**Comment by julien731** [comment]
Some styling is needed @SiamKreative . The link class is `wpas-forgot-password-link`.
