### ISSUE TITLE
Transients not being cleared when creating a new support user from the Dashboard

### ISSUE THREAD

**Issue by SiamKreative** [Awesome-Support/Awesome-Support#248]
If an administrator creates a new WordPress user, with the role "Support User", the transients are not cleared; Therefore the newly created support user won't show up in the "Ticket Creator" dropdown.

All support users (agents, users, etc) created via `Dashboard > Users > Create new` should trigger a transient reset.

**Comment by julien731** [comment]
Actually it should already be the case. Needs more testing.

**Comment by SiamKreative** [comment]
Actually, it seems to work just fine. I got confused because the **Display name publicly as** isn't automatically updated when editing the first name & last name. I thought it was, and therefore was looking for a name that no longer existed...

Would it be better to use first name & last name in the **Ticket Creator** drop-down?

![image](https://cloud.githubusercontent.com/assets/1778633/10988041/68e5468a-846b-11e5-8542-971139a50d00.png)
