### ISSUE TITLE
If agent replies by email to support user, links are broken

### ISSUE THREAD

**Issue by SiamKreative** [Awesome-Support/Awesome-Support#250]
![image](https://cloud.githubusercontent.com/assets/1778633/10841634/dae17c84-7f1d-11e5-909d-5e32deb8b152.png)

* The [View Ticket](https://getawesomesupport.com/wp-admin/post.php?post=164456&action=edit) link **points to the Dasboard (instead of the front-end)**
* or follow this link: https://getawesomesupport.com/testing-email-piping/ **points to a 404**

**Comment by julien731** [comment]
Can't reproduce. Have you tried refreshing your permalinks?
