### ISSUE TITLE
There is a filter name with a space in it

### ISSUE THREAD

**Issue by khag7** [Awesome-Support/Awesome-Support#252]
https://github.com/Awesome-Support/Awesome-Support/blob/efca760c4c23b5c7595697c1a73d7b7c8189257f/includes/class-email-notifications.php#L212

The filter name is `wpas email_notifications_cases_active_option` but it should be `wpas_email_notifications_cases_active_option`

In addition to changing it from a space to an underscore, the original typo'd filter name should continue to exist for backwards compatibility.

**Comment by SiamKreative** [comment]
Well spotted @khag7 ! Thanks for reporting this :)
