### ISSUE TITLE
Filter tickets by user / Ticket history per user

### ISSUE THREAD

**Issue by SiamKreative** [Awesome-Support/Awesome-Support#254]
As pointed out by **Jamie Stephens**:
> I would like to know if there is a way that I can view ticket history for a client.  For example, if a user named “Joe123” writes in a new ticket, is there a way that we can see what other tickets that user has submitted?

> In our experience, a lot of people will create new tickets and reference previous issues — we’d really like a way to be able to see previous tickets for each user.

> I’m assuming since everything is stored in the database, this is possible — but wondering the best way to accomplish this?

### Possible UI/UX improvements
I completely agree with Jamie, and I therefore suggest to:
* Add a link "View all tickets for this user", in the Stakeholders metabox (Dashboard > Edit ticket)
* or Create a new metabox "Tickets created by XXX", which actually list the 5 last tickets (Dashboard > Edit ticket)
* Add new column "Ticket creator" in Dashboard > All tickets, with clickable username

**Comment by SiamKreative** [comment]
Work in progress:
![image](https://cloud.githubusercontent.com/assets/1778633/10975191/468897a2-8418-11e5-9b12-e8c5b827777a.png)

**Comment by SiamKreative** [comment]
* Add hover hint 1c666cb
* Add style for user profile metabox e369ce6
* Add minimalist grid system 871b045
* Add User Profile metabox 2e26c95

**Comment by SiamKreative** [comment]
@julien731
- [ ] Properly load `simple-hint.min.css` (currently loaded from CDN within `user-profile.php`)

**Comment by julien731** [comment]
See cbe9d79b6b553742a84117f26a33ddd60d1c2c4f
