### ISSUE TITLE
Prepurchase question: Use new Envato OAuth API

### ISSUE THREAD

**Issue by vburlak** [Awesome-Support/Awesome-Support#264]
Interested in purchasing Envato Verification extension.
Envato released a [new API](https://build.envato.com/api/) with such feature as a OAuth and etc. 

I wonder whether the plugin will be support the new API, and when?
Cheers!

**Comment by julien731** [comment]
The Envato addon already uses the latest version of the Envato API ;)

**Comment by vburlak** [comment]
@julien731 thanks for reply. 
In this case, users do not have to go through all this pain with api keys?
It will be very cool to see detailed demonstration video at [add-on page](https://getawesomesupport.com/addons/envato-validation/) or some live demo :)

**Comment by julien731** [comment]
We actually don't use OAuth because this is a distributed app. What you'll need to do is [generate a "personal token"](https://build.envato.com/create-token/) in order to authenticate.

**Comment by vburlak** [comment]
@julien731 I have read all documentation completely.
I'm just mean all pain with api keys for customers when they authorizing via Envato Verification extension.

Does customers need to verify their license going to themeforest/codecanyon profile, choosing product, and copying their purchase code and inserting it in a Aswesome Support profile page? Or it will be done automatically via getting buyer purchases in your Extension?

**Comment by julien731** [comment]
Oh yeah, users submitting a ticket must provide their purchase code.

**Comment by vburlak** [comment]
@julien731 New Api have [List Buyer purchases method](https://build.envato.com/api/#!/market_0/Buyer_ListPurchases). Using this method extension can get user's purchases, license type and purchase code. 

It will be very great to see implementation of this method in future release of Envato Verification add-on.
And it will be greatest and simplest Auth method for potential customers.
Regards!

**Comment by julien731** [comment]
I completely agree with you about the simplicity. However, that would require registering the app for each user of the Envato addon.

I'm not closing the door here, but if you want to keep discussing this, let's keep the talks in the [addon roadmap](https://trello.com/c/QlewI8Wd) as GitHub is only used for the core plugin.

**Comment by SiamKreative** [comment]
Perhaps this can help

https://github.com/envato/wp-envato-market
https://forums.envato.com/t/envato-market-wordpress-plugin-beta/21639

**Comment by vburlak** [comment]
@SiamKreative thanks for the reference. I'm already tested new envato market.

@julien731 dtbaker also creating another great plugin for his themes: [Envato Wordpress Theme Setup Wizard](https://github.com/dtbaker/envato-wp-theme-setup-wizard)
One of the feature of this setup wizard — ability to verify purchase via new Envato Market Plugin using OAuth method. [Short video demo, how it looks and works](https://www.youtube.com/watch?v=vMey1BrKP_A) for customer.

Also, it's [require register the app for each author](https://github.com/dtbaker/envato-wp-theme-setup-wizard#setup-instructions), who is going to use this plug-in to verify the license.
Api keys and purchases codes is a technology from the last century :smiley:

Well, I'll be happy to continue the discussion in the roadmap.
