### ISSUE TITLE
Products Dropdown Improvement

### ISSUE THREAD

**Issue by julien731** [Awesome-Support/Awesome-Support#268]
On the front-end, when a site has lots of products (let say 100+), it can become quite messy. The end user will have to scroll through hundreds of products to find the right one.

In average, our users don't have that many products, but maybe we could have an option somewhere to enable select2 on this dropdown for users who do.

**Comment by SiamKreative** [comment]
The only issues that comes to my mind when I think about this is that:
* It might be tough to get a consistent styling of the select2 dropdown across various themes
* It will slightly after the page load

Also, should it be a general options for products? Or should the option also be available for custom fields?

**Comment by nachumie** [comment]
I found that amazing solution:
https://harvesthq.github.io/chosen/

There is a wp plugin called "Chosen for WordPress" 
All i needed is to include [chosen] within the "Submit ticket" page.

Done.

**Comment by SiamKreative** [comment]
* https://select2.github.io/
* https://selectize.github.io/selectize.js/
* https://harvesthq.github.io/chosen/

**Comment by SiamKreative** [comment]
@julien731, I'm guessing there's no way to have `<optgroup>` for users who want to categorize their products?

Does the Select2 library have to be bundled in the plugin's JS, or can it be loaded separately on per case basis (if users has enabled the option on one custom field or more)?

**Comment by julien731** [comment]
1. No `optgroup` indeed
2. Both options are possible

**Comment by SiamKreative** [comment]
When the option select2 is `true` for the custom fields select:

- [ ] Enqueue Select2 assets (assets\admin\css\vendor\select2.min.css + assets\admin\js\vendor\select2.min.js)
- [ ] Enqueue custom component (assets\public\js\component_ticket.js which is not yet created)
- [ ] Add meaningful class to the select (perhaps `.wpas-select2`)

**Comment by julien731** [comment]
There is one more issue to address before closing this task: the select2 assets are registered twice. It's registered once in `scripts.php`, but because it is normally used in the admin, the assets are registered again when the custom field is registered.

We need to find a way to centralize that. Registering assets twice is stupid and will only lead to forgetting to update it when necessary.

**Comment by SiamKreative** [comment]
- [ ] Add documentation on "How to enable Select2 on select dropdowns (products, custom fields)"
