### ISSUE TITLE
Move tickets with recent replies to the top

### ISSUE THREAD

**Issue by SiamKreative** [Awesome-Support/Awesome-Support#271]
Currently, tickets are not sorted by latest replies. This means that a support agent has to scroll down all the way to see tickets with the most recent activity "Awaiting Support Reply".

This is a terrible UX mistake. All ticket systems normally behave the same as an email inbox, showing the most recent conversation at the top...

**Comment by SiamKreative** [comment]
@AGSoftAU I tried your changes on the branch develop and they don't work. There is no change in the tickets order.

**Comment by julien731** [comment]
PR #284 was a good start but it doesn't work as expected. Details are available in the PR conversation. More work is needed on the SQL query to correctly sort tickets.

The correct order should be:

1. Tickets with no reply
2. Tickets last replied by the client (awaiting agent reply)
3. Tickets last replied by the agent (awaiting client reply)

**Comment by julien731** [comment]
See #311
