### ISSUE TITLE
Support agents can't see attachments

### ISSUE THREAD

**Issue by SiamKreative** [Awesome-Support/Awesome-Support#275]
When a support user or admin attaches a file to a ticket (via front-end or Dashboard), support agents don't see the attachments.

Is this some kind of permission issue?

**Comment by julien731** [comment]
Shouldn't be, there is no capability check for displaying attachments. Maybe it's a bug in the query itself.

**Comment by SiamKreative** [comment]
Okay so, enabling Filepicker addon doesn't help whatsoever.

The agent is only able to see his own attachments.

**Comment by BurlesonBrad** [comment]
USE THIS! ----> https://gist.github.com/BurlesonBrad/b2b6ce4957bc22e074f5  :wink: It works Awesome for the customer as well.  We just need to assign the attachment to a ticket.  
_**bonus feature**_ would be to integrate Amazon S3 offloading of these attachments

**Comment by SiamKreative** [comment]
As of Monday, March 28, 2016, this is no longer a problem.
