### ISSUE TITLE
Add Logout Link

### ISSUE THREAD

**Issue by julien731** [Awesome-Support/Awesome-Support#278]
An increasing number of users are asking for a logout link on the tickets pages.

**Comment by SiamKreative** [comment]
* Should it be optional?
* Should it be enabled by default?

I think it should be shown for all, without an option to hide it. I don't think we should worry about making it optional because it's as simple as `.logout-button {display: none;}` to hide the logout button.

**Comment by SiamKreative** [comment]
https://codex.wordpress.org/Function_Reference/wp_logout_url
