### ISSUE TITLE
More Performance Issues with Users Lists

### ISSUE THREAD

**Issue by julien731** [Awesome-Support/Awesome-Support#285]
As [reported by Dylan](https://wordpress.org/support/topic/scalability-of-plugin-with-over-9000-users-), the plugin still struggles with listing users on installs with a large users database.

Full report is available here: https://wordpress.org/support/topic/scalability-of-plugin-with-over-9000-users-

In order to bypass that issue, we could maybe use `$wp_roles` to get the roles with the appropriate caps first, and then query users with those roles.

**Comment by irkanu** [comment]
Not sure if commit 45e25f3 affects other areas, but this is our current workaround.

**Comment by julien731** [comment]
If doing the SQL query manually solves the problem it means it's really just the `update_meta_cache()` that causes the slowdown. I wonder why there is no option to deactivate it during the query just like in `WP_Query`.

**Comment by irkanu** [comment]
Is it because role is a meta query and the query method of WP_User_Query fires:

`		if ( 'all_with_meta' == $qv['fields'] ) {
			cache_users( $this->results );`

And cache_users fires:

`	update_meta_cache( 'user', $ids );`

I'm fairly new to actually cracking open Core, so forgive me if I'm way off.

**Comment by marbetschar** [comment]
Same issue over here using a user database containing 4'500 users. As you can see in the following screenshots, Awesome Support nearly doubles the page load time :(

Any solution for this?

P3 Results **before** activating Awesome Support
![before](https://cloud.githubusercontent.com/assets/392542/13725694/8b907e0a-e8a9-11e5-9d31-c87fa3f42850.png)

P3 Results **after** activating Awesome Support
![after](https://cloud.githubusercontent.com/assets/392542/13725695/913f82d8-e8a9-11e5-94ec-e6e663d9b7d6.png)

**Comment by julien731** [comment]
A few improvements underway in the [`users`](https://github.com/Awesome-Support/Awesome-Support/tree/users) branch, mostly helping reduce the number of caching queries done per user, but this still won't fix the problem with DBs containing more than 6/7,000 users.

The users management is a really big pain in the ass and WordPress doesn't really offer efficient solutions in this particular scenario.

There are a couple of solutions I have in mind but none of them sounds too appealing so far:

1. Use a custom database table for AS users
2. Force users to pre-load full AS users list

**Comment by marbetschar** [comment]
Just as idea, without knowing too much about the underlying details: Isn't this "just" a querying issue?

If so, maybe some sort of "asw - speed - optimized - wrapper" or "lightweight - user - querying - wrapper" mocking the WordPress User API may help?

**Comment by marbetschar** [comment]
PS: And what are WordPress core dev's saying about this topic? Sounds like those should really take care about the problem?

**Comment by SiamKreative** [comment]
I have create a [Google Forms to help follow up on the performance issue](https://docs.google.com/forms/d/1eOZR71DGCkzBwrqYq8OVH5JLTVMOvk7dLJwFcS-Fiws/viewform), and I’d be grateful if you could all fill it out.
