### ISSUE TITLE
Split JavaScript by components + Add SourceMap

### ISSUE THREAD

**Issue by SiamKreative** [Awesome-Support/Awesome-Support#286]
## Split by components

Instead of having a big file, namely `public.js`, we should divide it into components. For instance:

* `component-helpers.js`: helper functions (stringToBool, clearFileInput)
* `component-registration.js`: contains everything related to registration form (featherlight, hideShowPassword, email validation with Mailgun)
* `component-upload.js`: contains everything related to uploads
* `component-ticket.js`: contains everything related to ticket (ticket creation & replies)

This would make everything much clearer and easier to maintain.

## Add SourceMap

So far, it was hard for me to debug client sites because the JavaScript was minified. Even if I could expand the source, it's still hard to figure out from why source file does an issue come from (because variables names are mangled).

With SourceMap, everything gets easier...

**Comment by julien731** [comment]
+1

**Comment by SiamKreative** [comment]
Loop through the folder using Gulp / Grunt and compile them together.

**Comment by SiamKreative** [comment]
b2891fdff37bc1cdbfe97204e1fef27f84861faa
