### ISSUE TITLE
Awesome Support assumes that because WooCommerce is installed, you must want product sync

### ISSUE THREAD

**Issue by malcolmgroves** [Awesome-Support/Awesome-Support#288]
I have a website that includes woocommerce, but I do NOT want to synschronise my woocommerce products with the AS products (strictly speaking I want to selectively sync some of them, but as this is not possible now, I'll maintain the AS products outside woocommerce).

Anyway, I could not figure out how to turn off the woocommerce product sync, there doesn't seem to be an option. Debugging, I found out why. is_woocommerce_enabled in class-product-woocommerce is implemented to check if woocommerce is installed, and if so, assume that the integration should be enabled. 

I have changed this in my install to simply return false, but this is a hack. I understand that I'm probably in a minority, that most people who have both AS and WC installed probably want them sync'd, but it would be nice if there was a way to disable it without manually altering the class, as I now have to be careful to reinstate this hack every time I upgrade AS. 

Cheers
Malcolm

**Comment by julien731** [comment]
Hi Malcolm,

I agree with what you said. Assuming users want to sync their products just because they have en e-commerce plugin active is wrong. The user should be able to decide how they want AS to behave.

We will definitely change how this works.

**Comment by malcolmgroves** [comment]
wow, that's amazingly responsive Julien. 2 minutes from reporting to response! Very impressive.

Cheers
Malcolm
