### ISSUE TITLE
An invalid form control with name='wpas_user_reply' is not focusable.

### ISSUE THREAD

**Issue by SiamKreative** [Awesome-Support/Awesome-Support#290]
See https://github.com/Awesome-Support/Awesome-Support/blob/master/assets/public/js/public.js#L34-L40

This function will only work with textarea, not TinyMCE...

**Comment by SiamKreative** [comment]
Simplify the code c7eae37fbc1a0756ab6d9ccc36483e8994765e8a

**Comment by lucianopreza** [comment]
Hi Siam, I have the problem to reply a message with attachment, I copy and paste the code below but the problem continuous..

The same problem report by andrew55 Posted 1 month ago
https://wordpress.org/support/topic/upload-not-working-on-replies-only


**replyForm.on('change', replyClose, function () {
			// Check if textarea is focusable
			if (replyInput.is(':visible')) {
				// If "Close this ticket" checkbox is checked, add required attribute to textarea 
				replyInput.prop('required', replyClose.is(':checked'));
			}
		});**


Please could you try help me?

Está é minha pagina.
http://kinix.com.br/?page_id=107

This is my page if you open a ticket and then immediately try to attach a file to send the button does not respond nothing happens.

Thanks
