### ISSUE TITLE
Dashboard Widget

### ISSUE THREAD

**Issue by Laurel-Summit-Media** [Awesome-Support/Awesome-Support#299]
# feature request

Hi Julian,

I would like to see a a dashboard widget for agents who have ticket assignment privileges. This widget would be very useful so that an agent who is assigned to a ticket can see if tickets have been responded to by customers and if that ticket needs further attention. This would be a very powerful tool for organizations like mine, who use WPAS exclusively for product and customer support.

**Comment by SiamKreative** [comment]
Hi Nicholas,

Not sure I understand the purpose of this widget. Where should it be displayed? And what does it do exactly?

**Comment by nschvabenitz** [comment]
The widget would be displayed on the support agent's WP Admin Dashboard. The purpose of the widget would be very simple. It's a quick and easy way for that specific agent to see all of the "open" tickets that are assigned to them. This way, the support agent does not need to navigate to the Tickets screen and sort through many many pages to find the ticket he or she needs to respond to. 

It would be a great housekeeping tool.

My company uses WPAS exclusively for customer service and support. We have 5 agents. All of which have been complaining that the process of locating tickets that are assigned to them is cumbersome. They say sometimes they must go back several pages to find open tickets the've got and they wish there was an easier way for them to see the open tickets that are assigned to them (on a per-support user basis) right on their dashboard. 

I would really love to see something like this implemented. Especially for those who do a lot of ticket volume... Like our company.

**Comment by julien731** [comment]
Did you set Awesome Support to let all agents see all tickets?
