### ISSUE TITLE
Invite active plugin users to rate the plugin on WordPress.org

### ISSUE THREAD

**Issue by SiamKreative** [Awesome-Support/Awesome-Support#300]
I think it could be a good idea to invite only active users to rate the plugin. For instance, if more than 50 tickets have been opened, then trigger a modal:

![image](https://cloud.githubusercontent.com/assets/1778633/10988583/2874907e-8470-11e5-8046-02e9b0ade5a9.png)

> Congrats, you've unlocked a new badge! Thank you for using **Awesome Support** since November 5, 2015! Here are some usage statistics about your support site...
> If you like the plugin, please give it a [5-star rating on WordPress.org](https://wordpress.org/support/view/plugin-reviews/awesome-support?rate=5#postform) or Tweet about it :)

---
### What is an active plugin users?
- Capability: agent/admin
- Ticket activity: how many tickets have been opened/closed + amount of replies

---
### Way of inviting users to rate?
- Standard WordPress notice
- Modal (maybe using the built-in Thickbox)

**Comment by elindydotcom** [comment]
We didn't do a modal but we did add in a notice at the top of the plugins screen in 4.0.0.  The modal seemed too intrusive so skipped that option.  I like the badge idea for setting up competitions for resolving tickets and such.
