### ISSUE TITLE
Improve UI of Front-End Tickets List (table)

### ISSUE THREAD

**Issue by julien731** [Awesome-Support/Awesome-Support#302]
No pagination at the time. Maybe we should add one for cases where a user has lots of tickets.

**Comment by SiamKreative** [comment]
| Name        | Link                                         | Stars | Last Updated | Demos                                 |
|-------------|----------------------------------------------|-------|--------------|---------------------------------------|
| FooTable    | https://github.com/fooplugins/FooTable       | 1500+ | 14 days ago  | http://fooplugins.com/footable-demos/ |
| DataTables  | https://github.com/DataTables/DataTables     | 3500+ | 6 days ago   | https://datatables.net/examples/index |
| tablesorter | https://github.com/christianbach/tablesorter | 600+  | 5 months ago | http://tablesorter.com/docs/#Examples |

**Comment by SiamKreative** [comment]
@julien731 How comes the `<table id="wpas_ticketlist">` only shows 5 rows? Is there a setting that I'm not aware of?

**Comment by SiamKreative** [comment]
Also, we need to add the status to the row of each ticket (not only `open` and `close` like currently using `wpas_get_ticket_status( $wpas_tickets->post->ID )`.

**Comment by SiamKreative** [comment]
### What is left to do?
- [ ] Disable sorting for status column (`data-sort-ignore="true"`)
- [ ] Functional sort by date (need to add `data-type="numeric" data-sort-initial="true"` and change `data-order` to `data-value`)
- [ ] Show status dropdown only if ticket list has more than one ticket status

**Comment by SiamKreative** [comment]
Screencast to see what it looks like:

 [![image](https://cloud.githubusercontent.com/assets/1778633/15009999/0bb0f69e-1214-11e6-86e6-5b481ee98fb0.png)](https://dl.dropboxusercontent.com/u/28858864/screencasts/as_ticketlist_filters.mp4)

**Comment by julien731** [comment]
Regarding the tickets limit issue, I can't reproduce. The tickets list table is set to show all of the user's tickets.
