### ISSUE TITLE
The official repository of plugins

### ISSUE THREAD

**Issue by d4b** [Awesome-Support/Awesome-Support#305]
When can we expect an update in the repository WordPress?

**Comment by SiamKreative** [comment]
_Probably end of this month. _

Please use our [contact form](https://getawesomesupport.com/contact/) instead of Github for this kind of question. We use Github issues for technical stuff only.

**Comment by julien731** [comment]
You can actually see the progress of next version here: https://github.com/Awesome-Support/Awesome-Support/milestones/3.3

However, in the future, please use WP.org support forum for this type of question. GitHub is only used for bug reports and development related issues.
