### ISSUE TITLE
Conflict with Ninja Forms

### ISSUE THREAD

**Issue by julien731** [Awesome-Support/Awesome-Support#314]
A conflict with Ninja Forms has been reported on the WordPress.org support forum (https://wordpress.org/support/topic/fatal-error-as-soon-as-i-updated-to-new-version?replies=2#post-8465923).

The issue is caused by Ninja Forms using a non-original version of [Eric Mann's WP Session Manager](https://github.com/ericmann/wp-session-manager).

While the [`$session_id`](https://github.com/ericmann/wp-session-manager/blob/master/includes/class-wp-session.php#L25) property is `protected` in the original library, Ninja Forms changed it to `public`.

Because Awesome Support is loaded before Ninja Forms, our version of `WP_Session` is used with `$session_id` being `protected`.

Because dependencies are managed by Composer in Awesome Support, we can't just change the property visibility manually or it will be overwritten during next update.

[I have submitted a tiny PR](https://github.com/ericmann/wp-session-manager/pull/37) to WP Session Manager in order to change the visibility (it can indeed be useful to be able to access the session ID).

If this is accepted and merged then great. Otherwise, we'll need to find another solution.

**Comment by ericmann** [comment]
As much as I don't like it - you shouldn't be accessing the session ID directly! - I've accepted the PR to help solve this issue.

**Comment by julien731** [comment]
To be honest I don't even need it. However, I've seen a couple of plugins doing that ([Ninja Forms](https://github.com/wpninjas/ninja-forms/blob/master/deprecated/includes/libraries/class-wp-session.php#L36), [EDD](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/libraries/class-wp-session.php#L28)).

Because Awesome Support's version is often loaded first and it is the genuine one (included using Composer) it causes issues.

May I ask why you don't like the session ID to be accessed directly?

Thanks for the merge btw.

**Comment by ericmann** [comment]
It's unnecessary visibility and there's no write protection on the field. The ID was meant to be an internal reference only and, earlier on when it _was_ publicly accessible, people were overwriting it frequently by mistake and breaking their code.

**Comment by julien731** [comment]
Oh, I see yeah. So ideally there should be a public method to access it instead of accessing `$session_id` directly? That would make sense.

I understand your position. In my case, I'd rather use the "stock" version of WP Session Manager instead of hacking it, which is why I've created the PR. If you really don't feel comfortable with that, though, you could revert it and create a new method for retrieving it and I could try to ask other authors to update their plugin(s) to use the latest method for retrieving the session ID.

**Comment by ericmann** [comment]
No, this is fine. I haven't updated the plugin in ages anyway and have a non-backwards-compatible replacement in the planning stages anyway.
