### ISSUE TITLE
Compatibility with WooCommerce 2.6 Tabs

### ISSUE THREAD

**Issue by nschvabenitz** [Awesome-Support/Awesome-Support#327]
Can you please tell me when you plan to add support for the WooCommerce 2.6 update? So that the tickets are displayed under their own tab in WooCommerce? Right now they are displaying under the Dashboard Tab.
![screen shot 2016-06-23 at 12 34 36 pm](https://cloud.githubusercontent.com/assets/18583977/16957736/a3a62c1c-4dab-11e6-9972-989ff6699f25.png)

**Comment by julien731** [comment]
This is coming in the next version of the WooCommerce addon. Because this is related to an addon, I'll close the issue now. We only use the issue tracker for issues related to the core plugin.
