### ISSUE TITLE
WooCommerce Plugin Doesn't Work After Tabs Support Added 11 Hours ago

### ISSUE THREAD

**Issue by nschvabenitz** [Awesome-Support/Awesome-Support#328]
Julian,

I've started to post here because for some reason my open tickets on your website are not being answered. The update that you released 11 hours ago Version 1.2.0 WooCommerce Awesome Support plugin... Does not work. The "Support Tab" directs customers to a "page not found" page.

Please review your code and release an update that works. My website is now broken and I have to restore from a backup.

**Comment by julien731** [comment]
Hi,

I believe you finally got an answer on the support. For future reference, this is most likely a simple permalinks issue that can be fixed by refreshing permalinks in WordPress.
