### ISSUE TITLE
Uninstall - products are not deleted

### ISSUE THREAD

**Issue by Ninos** [Awesome-Support/Awesome-Support#33]
After uninstalling the plugin, the products still exists :-)

**Comment by SiamKreative** [comment]
I just tried, and everything gets deleted including the products with the option checked.

**Comment by SiamKreative** [comment]
Actually. Forget about what I said in my previous comment. Products aren't deleted! @julien731

**Comment by SiamKreative** [comment]
Problem still occurs @julien731. See screencast https://www.youtube.com/watch?v=jrawwitA8qc (version 3.2.7)

**Comment by elindydotcom** [comment]
This issue with uninstall always deleting regardless of the flag  is fixed in 4.0.0.
