### ISSUE TITLE
Add Individual Option to See All Tickets for Admins

### ISSUE THREAD

**Issue by julien731** [Awesome-Support/Awesome-Support#331]
For admins, it would make sense to be able to show all tickets individually. This way, each admin can have his preferred view. If an admin needs to see all the tickets, others can still have their own personal view.

Actually, this should not be limited to admins, but it should be available to all users that have the capacity to see all tickets.

**Comment by elindydotcom** [comment]
This feature (actually a much more powerful version of it) is now part of our POWERPACK (Productivity) add-on. So closing this issue.
