### ISSUE TITLE
Conflict with ACF Pro

### ISSUE THREAD

**Issue by SiamKreative** [Awesome-Support/Awesome-Support#332]
ACF Pro uses Select2 3.5.2, which is loaded everywhere in the Dashboard. Therefore, it conflicts with our version (4.0.0)...

If multiple versions of Select2 are loaded, conflicts will arise!

**Comment by SiamKreative** [comment]
```php
<?php
function m_dequeue_script() {      
 wp_deregister_script( 'select2' );      
 wp_deregister_style( 'select2' );   
}   
add_action( 'init', 'my_dequeue_script', 20 );
?>
```

**Comment by julien731** [comment]
The first problem I see with this snippet is that it is extremely generic. The handle `select2` could be used by anyone. If really they use this handle to enqueue their version of select2 it is definitely not going to help.

I'll have a look at the source code of ACF Pro to double-check the handle they use.

**Comment by julien731** [comment]
In progress. See https://support.advancedcustomfields.com/forums/topic/select2-conflict-with-awesome-support/

**Comment by SiamKreative** [comment]
Seems that WC is also loading an outdated version of Select2: http://example.com/wp-content/plugins/woocommerce/assets/js/select2/select2.min.js?ver=3.5.4

**Comment by julien731** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;GSkBfAgd&#x2F;5-bug-fix-acf"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Bug Fix:  ACF</a>
