### ISSUE TITLE
PHP 7 Compatibility Issues

### ISSUE THREAD

**Issue by nschvabenitz** [Awesome-Support/Awesome-Support#334]
I am migrating to PHP 7 and I understand that Awesome Support is not compatible with PHP 7. Can you tell me when this compatibility will be available?

The errors being given for PHP 7 are as follows: 
## FOUND 4 ERRORS AFFECTING 4 LINES

 3445 | ERROR | 'string' is a reserved keyword introduced in PHP version 7.0 and cannot be invoked as a function (T_STRING)
 3643 | ERROR | Function name, class name, namespace name or constant name can not be reserved keyword 'string' (since version 7.0)
 3756 | ERROR | 'string' is a reserved keyword introduced in PHP version 7.0 and cannot be invoked as a function (T_STRING)

**Comment by julien731** [comment]
That's curious. Awesome Support itself (the core) is compatible with PHP7. Now, this error is coming from the Titan Framework. However, we do run the plugin on PHP7 ourselves and everything is fine.

First of all, if @bfintal could jump in regarding TF and PHP7 that'd be a great help. I'll try to ping him.

**Comment by nschvabenitz** [comment]
Any updates on this? I am starting to see a lot of errors in my error log on my server from awesome support.

**Comment by bfintal** [comment]
We were testing PHP 7 with Titan and wasn't running into problems. At least the error stems from scss.inc.php. Let me get back to you on this in a bit.

**Comment by bfintal** [comment]
Hey @nschvabenitz will you be able to test whether replacing the file `/www/public/wp-content/plugins/awesome-support/vendor/gambitph/titan-framework/inc/scssphp/scss.inc.php` with this makes the error go away?

https://gist.github.com/bfintal/60f303db3c6c3f27002d72ed45947dcb
