### ISSUE TITLE
Option to have Backend Only Custom Fields/Taxonomies

### ISSUE THREAD

**Issue by alpha1** [Awesome-Support/Awesome-Support#338]
It could be nice to have an option (set to true by default) that allows adding a custom field publicly, or backend only, so support reps can record internal notations. Use cases might be marking a ticket a duplicate, or keeping status of a report filed with an upstream provider or partner, or mark milestones tickets are (or should be) completed in.

**Comment by julien731** [comment]
I think that, based on the pretty small amount of work required for that feature, it is very likely something that we could add in. I can indeed see the use for front/back only fields.

**Comment by elindydotcom** [comment]
This has been added in version 4.0.
