### ISSUE TITLE
PHP Errors - Trying to get property of non-object

### ISSUE THREAD

**Issue by nschvabenitz** [Awesome-Support/Awesome-Support#342]
Hi Julian,

I'm still seeing WPAS generate PHP Errors (Trying to get property of non-object). These errors seem to be adding load time to my website on the front-end for users. I am counting close to an extra 2 seconds. This may be a PHP 7 specific error. I am running PHP 7.

Can you please have a look at this for me?

<img width="1266" alt="screen shot 2016-09-24 at 2 17 20 pm" src="https://cloud.githubusercontent.com/assets/18583977/18810342/c41249f0-8261-11e6-948f-4e6fe19a4474.png">

**Comment by julien731** [comment]
Could you please open a thread on WP.org for support. This seems to be an issue with the e-commerce products sync.
