### ISSUE TITLE
PHP syntax error

### ISSUE THREAD

**Issue by DanStorm** [Awesome-Support/Awesome-Support#346]
We use wpengine. They have git repos built in as part of their service. When you push to a wpengine repo, it performs a syntax check on all php files being pushed. If any file fails the syntax check, wpengine quits the push process. I get the following errors when pushing the Awesome Support plugin and the Awesome Support: E-Mail Support plugin

```
PHP Parse error: syntax error, unexpected ‘.’, expecting ‘)’ in – on line 10
remote: – warning: syntax Error Found in wp-content/plugins/awesome-support/vendor/composer/autoload_static.php …

PHP Parse error: syntax error, unexpected ‘.’, expecting ‘)’ in – on line 10
remote: – warning: syntax Error Found in wp-content/plugins/awesome-support-email-support/vendor/composer/autoload_static.php …
```

Looks like a problem with the way the magic constant **DIR** is being used, here is a stackoverflow question about it

http://stackoverflow.com/questions/8759905/concatenating-dir-constant-with-a-string-as-an-array-value-which-is-a-class

This is preventing us from being able to use versioning for our site, any help would be greatly appreciated.

Thanks!

PS: I also added this a support ticket on wordpress.org before I found this repo
https://wordpress.org/support/topic/php-syntax-error-5/

**Comment by julien731** [comment]
I have followed up on the WP.org thread.
