### ISSUE TITLE
Different Custom Fields for different Departments

### ISSUE THREAD

**Issue by mbtocalli** [Awesome-Support/Awesome-Support#347]
I have read the documentation about Adding Conditional Logic and the other one about Custom Fields. I can't find any solution to add custom fields based on the Department you have choosed. Is that even possible?

**Comment by mbtocalli** [comment]
Ok, I just solved it. Using the department ID (taxonomy ID) into the conditional logic is possible to achieve what I asked before.

**Comment by SiamKreative** [comment]
If you don't mind sharing, I think it could help other users :)

**Comment by mbtocalli** [comment]
Sure! Using this file as reference:
https://gist.github.com/SiamKreative/735845931f04a9a44f6b

Since the ID name of the Departments dropdown selector is "wpas_department" (thanks to Firebug) and, in my case, the ID number of the department that should have additional fields is 173, I have edited the code from line 39 to 46 to look like this:

```
	$('select[name="wpas_department"]').on('change', function () {
		// Show additional field if the selected option is the one with ID=173
		var visible = ($(this).val() == '173') ? true : false;
		$('#wpas_my_custom_name_wrapper').toggle(visible);

		// Remove the required attribute when the field is hidden
		$('#wpas_my_custom_name').prop('required', visible);
	}).change();
```
