### ISSUE TITLE
Hide empty fields in backend

### ISSUE THREAD

**Issue by mbtocalli** [Awesome-Support/Awesome-Support#349]
I have a Support Form with several custom fields and conditional logics. For instance, if you choose option A in a select field you must complete custom fields A1, A2 and A3, but if you choose option B then you must complete custom fields B1, B2 and B3. If the client send the ticket choosing option B, I dont want'to see all custom fields of A in my backend. Can I use some function to hide empty fields in my backend?

**Comment by julien731** [comment]
Hey. It sounds like this could be done. However, we only handle support on the WordPress.org support forum or on our priority support if you're a paying customer.

I'm going to close this issue now and let you re-open it on the appropriate channel.
