### ISSUE TITLE
Need to be able to see all AWAITING REPLY tickets

### ISSUE THREAD

**Issue by rejon** [Awesome-Support/Awesome-Support#467]
Alot of our workers are getting lost because there are tickets they cannot see on page 1 of tickets, that need answering.

**Comment by elindydotcom** [comment]
I like this idea a lot.

**Comment by rejon** [comment]
Cool, yes,  seriously my workers are not replying to tickets because they
are buried in pages. Major usability real world usage problem.

**Comment by elindydotcom** [comment]
Added to V 4.1.0
