### ISSUE TITLE
When viewing orders in Woocommerce, allow Admins to create ticket

### ISSUE THREAD

**Issue by rejon** [Awesome-Support/Awesome-Support#468]
Often when looking at an order, would be ideal to just create a ticket for a customer immediately from the woocommerce order. Then the new ticket should be connected to the order so easier integration.

**Comment by elindydotcom** [comment]
I believe that this was already added to our [WOOCOMMERCE add-on](https://getawesomesupport.com/addons/woocommerce/).    If you're a license holder for that add-on you should be able to download the latest version (1.4.1).

**Comment by rejon** [comment]
dont see it in latest version

is it released yet?

jon

**Comment by elindydotcom** [comment]
Should be in 1.4.1 according to the developer.  What version are you running?

**Comment by rejon** [comment]
1.4.1

**Comment by elindydotcom** [comment]
@rejon  - best to open a support ticket on this so you can communicate to our WC expert.

**Comment by elindydotcom** [comment]
I'll also be closing this issue since WC features beyond basic product sync aren't part of the free core plugin and therefore doesn't belong in a discussion on here.
