### ISSUE TITLE
Added file types not allowed

### ISSUE THREAD

**Issue by cdillon** [Awesome-Support/Awesome-Support#474]
File types added in Settings > File Upload are not being added to the allowed mime type list on new tickets and new replies on the front end. In my case: txt, json, zip.

`wpas_is_plugin_page` is returning false in `WPAS_File_Upload->custom_mime_types` because it checks for the global $post but $post is not set yet.

The form actions are run on the `init` hook but the $post is not set until the `wp` hook.

A workaround is to add the extra mime types via the `upload_mimes` filter in another plugin.

A solution may be to add a check for `$_POST['wpas-do']` equal to `submit_new_ticket` or `submit_new_reply` in `custom_mime_types`.

**Comment by elindydotcom** [comment]
@cdillon  - we just tested this on a new install of AS on WordPress 4.8.  We added the TXT extension to the allowed file types in TICKETS->SETTINGS->FILE UPLOAD and then submitted a ticket on the front end with a file with the .txt extension.  (The .txt extension was not allowed before we added it).  The file was uploaded properly.
