### ISSUE TITLE
A lot of issues need fixing.

### ISSUE THREAD

**Issue by Forkin** [Awesome-Support/Awesome-Support#510]
Issue 1: 
It is mandatory to provide a description for your issue.

Can not create support tickets. If a user tries to create a ticket, it will throw this error, even if the description is already entered.

Issue 2:
The TinyMCE editor doesn't work for tickets either. You can not edit your text with the TinyMCE editor.

Issue 3:
The show password checkbox doesn't actually show the password.

**Comment by elindydotcom** [comment]
These all sound like conflicts with a plugin or theme.  If you can identify which plugin or theme is conflicting we can add it to this issue.  Without that information there's not much we can do with this report unfortunately.

**Comment by elindydotcom** [comment]
Closing because of lack of response from author.
