### ISSUE TITLE
Change ticket status when customer replies?

### ISSUE THREAD

**Issue by nutsandbolts** [Awesome-Support/Awesome-Support#544]
If there is an option for this, I apologize, but my Google Fu is failing me. I'm surprised to see there is no way to change the ticket status when a reply is received. For example, an agent might change the status to "awaiting reply" after answering, but if the customer responds, the status would update to "attention needed" (or whatever). This makes it easier to see which tickets in the list are in need of attention versus those that can be ignored. 

I know the "Awaiting Support Reply" thing shows up on the right, but we'd like to see the status changed as well since instinct is to look at the labels down the left side of the screen first.

**Comment by elindydotcom** [comment]
There is a premium add-on for Awesome Support - the [Business Rules Engine](https://getawesomesupport.com/addons/business-rules-engine-zapier-integration/) that allow this status transition to occur.

I'll leave this issue open in case another developer wants to contribute to the core code to add this option; but the core developers have already added it into the rules engine so they'll probably not move it into this core.

**Comment by nutsandbolts** [comment]
Thanks for the quick reply. We got it worked out just a moment ago, but I wish I had known the extension had that capability before I wasted the brain cells! :)

**Comment by Mohal** [comment]
@yeisonbp , review this. I think we can close this issue.
