### ISSUE TITLE
$(...).wpColorPicker is not a function

### ISSUE THREAD

**Issue by nmoinvaz** [Awesome-Support/Awesome-Support#593]
I have encountered a Javascript error when using Awesome-Support with GravityForms plugin.

![image](https://user-images.githubusercontent.com/1364432/41322060-c8a4d86a-6e5b-11e8-9849-2adddb0cdab1.png)

This happens when clicking "Forms" and then pressing the "Add New" button in Gravity Forms. It happens I believe because for some reason TitanFrameworkOptionColor->display() is not being called but TitanFrameworkOptionColor->startColorPicker() is.

A simple solution I have come up with is to do this inside of TitanFrameworkOptionColor:

```
public function startColorPicker() {
    ?>
    <script>
    jQuery(document).ready(function($) {
        "use strict";
        if ($('.tf-colorpicker').hasOwnProperty("wpColorPicker")) {
            $('.tf-colorpicker').wpColorPicker();
        }
    });
    </script>
    <?php
}
```

**Comment by nmoinvaz** [comment]
I think I can wait for the next release. It is just a pain when upgrading.

**Comment by nmoinvaz** [comment]
I see you are upgrading Titan Framework for 5.9.0. Much appreciated. Thanks!

**Comment by elindydotcom** [comment]
Wanna help test it? You can get the latest full pre-release 5.9 version here:  https://getawesomesupport.com/coming-in-early-2019-awesome-support-v-5-9-0/

**Comment by nmoinvaz** [comment]
Considering that I no longer have a way to test this and the required framework has been upgraded I'm closing this issue.
