### ISSUE TITLE
Trim extra whitespace on replies

### ISSUE THREAD

**Issue by nmoinvaz** [Awesome-Support/Awesome-Support#612]
It seems on some replies there is an extra `<p>&nbsp;</p>` that the Wordpress editor adds at the end. It would be great if Awesome Support could trim this extra white space when displaying a reply on the admin side and on the user side. I think it would make the replies look cleaner. Thanks!

**Comment by nmoinvaz** [comment]
I was able to achieve this by using:

```
add_filter( 'the_content', 'astrim_the_content' );
 
function astrim_the_content( $content ) {
 	$post_type = get_post_type();
	if ( $post_type == 'ticket' || $post_type == 'ticket_reply' ) {
		return preg_replace('/'.preg_quote('<p>&nbsp;</p>', '/').'$/', '', $content);
	}
    return $content;
}
```

Also this CSS helped:

```
.wpas-reply-content p:last-child {
	padding-bottom: 0px;
}
```

**Comment by nmoinvaz** [comment]
It might be worth it to put this into the productivity plugin under the Editor buttons tab.

**Comment by nmoinvaz** [comment]
I believe the setting for "Force Single Line Breaks" has been added. Would you be open for a pull request that adds an option for a setting that was like "Trim Extra Whitespace" from ticket content in "Style" tab?

**Comment by elindydotcom** [comment]
@nmoinvaz - yes, we would be open to that.

**Comment by Mohal** [comment]
Hey @nmoinvaz , I am closing this.
