### ISSUE TITLE
Make Dropzone JS timeout configurable

### ISSUE THREAD

**Issue by nmoinvaz** [Awesome-Support/Awesome-Support#616]
On large file uploads (say 100MB) the AJAX file uploader times out. I believe this is due to the timeout value on Dropzone JS the default of which is 30 seconds. It would be great if this value were configurable. For now I have hard coded it to 5 minutes.

https://gist.github.com/nmoinvaz/b0203fc50ce14cd8f71bae3a04d556d0

**Comment by nmoinvaz** [comment]
It might be a good idea to make the default equal to php's ini value of `max_execution_time`. In otherwise if one is smaller than the other, Dropzone JS might timeout or php might timeout.

**Comment by elindydotcom** [comment]
Updated the code to pull the timeout value from the ini file.  Its set to 30 if not able to pull it for some reason. Commit is [here](https://github.com/Awesome-Support/Awesome-Support/commit/9997275fa7d5130e061a8f713c28898290a9c723).

**Comment by nmoinvaz** [comment]
Nice! Thank you.
