### ISSUE TITLE
Arbitrary expressions in empty are allowed in PHP 5.5 only

### ISSUE THREAD

**Issue by cdillon** [Awesome-Support/Awesome-Support#652]
As reported by PhpStorm in 
awesome-support/includes/gdpr-integration/gdpr-privacy-options.php::L106-107

`$_status = (isset( $_GET['_status'] ) && !empty( isset( $_GET['_status'] ) ))? sanitize_text_field( $_GET['_status'] ): '';`
`$consent = ( isset( $_GET['_consent'] ) && !empty( isset( $_GET['_consent'] ) ) )? sanitize_text_field( $_GET['_consent'] ): '';`

**Comment by Mohal** [comment]
@cdillon 

Can you please send in a Pull Request (PR)?

**Comment by Mohal** [comment]
@yeisonbp this is fixed and merged.
