### ISSUE TITLE
Issue in fetching slug for Submit ticket in woocommerce menu

### ISSUE THREAD

**Issue by iamguni** [Awesome-Support/Awesome-Support#704]
Hi,

I was facing an issue in fetching slug for "submit ticket" link in my account page of woocommerce.
**get_endpoint_name_for_openticket_page** the function was returning page_id=0 and resulting a slug=0. So I have udpated this function in my webapp, Requesting team to verify and update the same, so the change may reflect globally.

**Old Code :** 

```
public function get_endpoint_name_for_openticket_page() {
		
		$slug = false ;  // return value
		
		$page_ids = wpas_get_option('ticket_submit') ;  // get the ids of the ticket pages from settings...
		
		if ( ! empty( $page_ids ) ) {
			
			$page_id = $page_ids[0];  
			$page = get_post( $page_id ) ;

			if ( ! empty( $page ) ) {
				$slug = $page->post_name;
			}

		}
		
		return $slug ;
		
	}
```

**New Code :** 

```
public function get_endpoint_name_for_openticket_page() {
		
		$slug = false ;  // return value
		
		$page_id = wpas_get_option('ticket_submit') ;  // get the ids of the ticket pages from settings...
		
		if ( ! empty( $page_id ) ) {
			
			//$page_id = $page_ids[0];  
			$page = get_post( $page_id ) ;
			//echo $page;
			if ( ! empty( $page ) ) {
				$slug = $page->post_name;
			}

		}
		
		return $slug ;
		
	}
```

![issue](https://user-images.githubusercontent.com/22880090/50422259-00d71b00-086f-11e9-8c24-9cc3c30f31c1.PNG)

**Comment by Mohal** [comment]
@iamguni ... can you send a pull request for this?

**Comment by Mohal** [comment]
Hey @iamguni ,

I have reviewed the issue you were facin' and don't see the issue happenin' on other websites. Plus, your suggested solution is not workin'.

So, closin' this issue.

CC: @yeisonbp
