### ISSUE TITLE
Allow Users to submit "Ideas" which can be voted by other users ==> most voted ideas will rise to the top

### ISSUE THREAD

**Issue by distributev** [Awesome-Support/Awesome-Support#706]
Similar idea with 

https://wordpress.org/plugins/ideapush/

https://github.com/imath/wp-idea-stream

It makes sense to use Awesome Support to gather new idea for the products - if we allow users to submit "bugs" submitting new ideas should also be allowed.

P.S - I noticed you are using Trello to "gather" ideas from users - https://trello.com/b/pHYdtkHc/awesome-support-roadmap

I believe you should be using Awesome Support for this :-)

**Comment by Mohal** [comment]
Not valid issue.
