### ISSUE TITLE
Change template root path not working

### ISSUE THREAD

**Issue by Johnny99211** [Awesome-Support/Awesome-Support#708]
I'm currently trying to override the template root path for the email templates in the `functions-tools.php` but the value is still the same:

```
add_filter( 'wpas_email_template_root_path', 'set_wpas_email_template_root_path', 30, 1 );
function set_wpas_email_template_root_path( $template_root_path ) {
	
	error_log( 'email-functions.php' );

	return get_home_path() . 'wp-content/themes/' . get_option( 'stylesheet' ) . '/awesome-support/emails/';
}
```

The variable I'm trying to override:

error_log( 'Before' );
// Allow other add-ons to set this path
apply_filters( 'wpas_email_template_root_path', $template_root_path );
error_log( 'functions-tools.php' . $template_root_path );

So I'm nut sure if this is a bug.

**Comment by elindydotcom** [comment]
Yup, that looks like a bug all right.  The apply filters statement on line 710 isn't being assigned to any variable.  Looks like the next version will fix it - download it from this link and see if that's better: https://getawesomesupport.com/coming-in-early-2019-awesome-support-v-5-9-0/

**Comment by Johnny99211** [comment]
I've made some changes and I'm not sure if I override them. I want to get all done and then I can do some updates. Do you have a hotfix for this file? Or can you say where the error happens? I'm sadly not good enough to find it since 2 days.

**Comment by elindydotcom** [comment]
No hot fix available but you can see the commit here: https://github.com/Awesome-Support/Awesome-Support/commit/4312c02a3e35bb369e943d807377610670e71f41

**Comment by Johnny99211** [comment]
Alright. And I'm right with my approach to set a custom template or is there a better solution for example overriding it like in WooCommerce? In WooCommerce you can copy the templates folder in the child theme and it's automatically overridden.
