### ISSUE TITLE
Product Sync is Broken

### ISSUE THREAD

**Issue by shazahm1** [Awesome-Support/Awesome-Support#713]
Opening this issue at the request of melliesou from the wp.org support forums.

Rather than repeat what was already communicated, please refer to my original post found here:

https://wordpress.org/support/topic/product-sync-broken-or-i-do-not-understand-it/

The tldr version...

Four issues:

 - All products are imported correct but are editable within AS. Editing a product in AS breaks the "link" to the imported product.
 - All products are synced regardless of the include/exclude options because on initial import those values are not taken into consideration.
 - The option import flag does not properly count the imported products.
 - The synced products will list in what appears in an odd order because the real product name is the synced object ID.

I've corrected these issues in the following commits:

 - https://github.com/shazahm1/Awesome-Support/commit/ea6b2ad92d120082840b49479854bfcf8d4f5109
 - https://github.com/shazahm1/Awesome-Support/commit/52171b606cbfd9e4fad7eca09c006245dd7dd948
 - https://github.com/shazahm1/Awesome-Support/commit/527efc6edef65621fb6e2051f1a1ac88589a5bbd

**Comment by shazahm1** [comment]
Unfortunately, the fixes were not made to 6.0.x, so I had to merge the changes manually. I hope these will be merged for the next update.

**Comment by Mohal** [comment]
Thanks

Pull request merged.
