### ISSUE TITLE
Admin List Last Reply Display Name

### ISSUE THREAD

**Issue by shazahm1** [Awesome-Support/Awesome-Support#715]
This confused me until I looked at the code. The ticket last reply author name is displayed as the user permalink slug.

See here:

 - https://github.com/Awesome-Support/Awesome-Support/blob/5.8.0/includes/admin/class-admin-tickets-list.php#L514

Please consider changing it from `$last_user->nicename` to `$last_user->display_name`.

This would also make  it more consistent since `display_name` is used elsewhere in AS.

**Comment by Mohal** [comment]
Hey @shazahm1 , create pull request for this.
