### ISSUE TITLE
Add filter for frontend reply types

### ISSUE THREAD

**Issue by nmoinvaz** [Awesome-Support/Awesome-Support#722]
In _wpas_get_replies_ it might be useful to have a filter for the post_types. In the private notes plugin there is _wpas_replies_post_type_, so in functions-post.php we could add:

```
'post_type' => apply_filters( 'wpas_frontend_replies_post_type', [
   'ticket_reply'
] ),
```

This would allow me to add the _ticket-note_ post type to be displayed for users that are agents from the private notes plugin.

In _partials/ticket-reply.php_ it would be necessary to also include the post type as a tr css class:

```
<tr id="reply-<?php echo the_ID(); ?>" class="wpas-reply-single wpas-status-<?php echo get_post_status(); ?> wpas_user_<?php echo $user_role; ?> wpas-<?php echo str_replace("_", "-", get_post_type()); ?>" valign="top">
```

**Comment by Mohal** [comment]
Not relevant in all use cases.
