### ISSUE TITLE
Activating Awesome Support Plugin causes TinyMCE editor to not show in another plugin

### ISSUE THREAD

**Issue by Controlhaus** [Awesome-Support/Awesome-Support#723]
It looks like Awesome Support is enqueuing tinyMCE on ALL admin pages, rather than just the ones it needs.

This causes the TinyMCE editor to not show in the admin page of other plugins (ZeroBS CRM Mail Campaigns in this case.)

**Comment by elindydotcom** [comment]
Looks like this issue is fixed in commit #https://github.com/Awesome-Support/Awesome-Support/commit/25a36c7a7d68f0681e0d95e9202486ef9659b7a4
