### ISSUE TITLE
PHP 7.3 Compatibility

### ISSUE THREAD

**Issue by glagonikas** [Awesome-Support/Awesome-Support#725]
Running PHP 7.3 we came across this warning
>PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

This seems to be caused by https://github.com/Awesome-Support/Awesome-Support/blob/develop/includes/class-product-sync.php#L242

In this line, `continue;` should probably be updated to `break;`

**Comment by elindydotcom** [comment]
Looks like this issue is fixed in commit #25a36c7 (but not yet released).

**Comment by IgorCode** [comment]
@elindydotcom Last release was on Sep 15, 2018 (198 commits to develop since this tag), any plans to create new release soon?

**Comment by Mohal** [comment]
Issue has been resolved.
