### ISSUE TITLE
Ticket list in another plugin code

### ISSUE THREAD

**Issue by stefanpejcic** [Awesome-Support/Awesome-Support#726]
On my site I use a wc plugin that creates custom tabs on the my-account page and displays a content specified in that plugins something.php file

Im trying to display the content of the [tickets] shortcode in one of those tabs but cant get it to work.

https://github.com/Awesome-Support/Awesome-Support/blob/develop/includes/shortcodes/shortcode-tickets.php

How do you include this in a custom theme/plugin?

**Comment by elindydotcom** [comment]
This sounds like a technical support question that should be directed to the support staff on the awesome support website.  (www.getawesomesupport.com).
