### ISSUE TITLE
Importer Add-on + Help Scout's New API V.2

### ISSUE THREAD

**Issue by jdphiladelphia** [Awesome-Support/Awesome-Support#729]
Help Scout no longer lets users generate API keys.

As of July 2019, users do not have an option any longer to go to MY PROFILE / AUTHENTICATION / GENERNATE API KEY. Their legacy API v1 does not work.

Will the Importer Add-on be updated to work with this new API? 

PS. Here is the new PAI info: 

https://developer.helpscout.com/mailbox-api/

https://developer.helpscout.com/mailbox-api/overview/authentication/

https://developer.helpscout.com/mailbox-api/migration/transition-service/

**Comment by jdphiladelphia** [comment]
Importer Add-on uses Help Scout API 1.0 which was discontinued.

When will Importer Add-on use Help Scout API 2.0 so that my agency can begin using Awesome Support?

**Comment by Mohal** [comment]
@yeisonbp , please advise

**Comment by yeisonbp** [comment]
Already solved and released.
