### ISSUE TITLE
Problem with filter

### ISSUE THREAD

**Issue by Johnny99211** [Awesome-Support/Awesome-Support#730]
I've found a problem in the file `functions-tools.php` line `701`. You providing here following filter:

`apply_filters( 'wpas_email_template_map_to_files', $template_files );`

But this way the filter can't work because it's never using the value passed back to the filter. It needs to be: 
`
$template_files = apply_filters( 'wpas_email_template_map_to_files', $template_files );`

Please fix...

**Comment by elindydotcom** [comment]
Looks like this was fixed more than a year ago: https://github.com/awesome-support/awesome-support/commit/4312c02a3e35bb369e943d807377610670e71f41

It just hasn't been released yet.  You should drop the company a note to ask them about a new release that incorporates this fix.
