### ISSUE TITLE
Bug in ticket close redirect process.

### ISSUE THREAD

**Issue by asha23** [Awesome-Support/Awesome-Support#732]
I got the following bug on the redirect page when you close a ticket on the frontend using the checkbox.

`PHP Notice:  Undefined variable: ticket_id in ***plugins/awesome-support/includes/functions-post.php on line 694 `

I fixed it by changing the line to

`if ( $close && apply_filters( 'wpas_user_can_close_ticket', true, null ) ) {`

I'm not sure if this will have implications on the wider system. But thought I'd flag it.

**Comment by evertiro** [comment]
Is this still an issue? The current function enforces `$ticket_id` being an integer, and I don't have this particular error in my logs.

**Comment by Mohal** [comment]
This bug has been resolved.
