### ISSUE TITLE
A couple of PHP errors after upgrading to 6.0 version

### ISSUE THREAD

**Issue by bobmitro** [Awesome-Support/Awesome-Support#739]
Hi,

After upgrading to the latest version 6.0, I notice many PHP errors, e.g.

`Warning: require(/public_html/wp-content/plugins/awesome-support/includes/integrations/my-cred/my-cred.php): failed to open stream: No such file or directory in /public_html/wp-content/plugins/awesome-support/awesome-support.php on line 439

Fatal error: require(): Failed opening required '/public_html/wp-content/plugins/awesome-support/includes/integrations/my-cred/my-cred.php' (include_path='.:/opt/cpanel/ea-php73/root/usr/share/pear') in /public_html/wp-content/plugins/awesome-support/awesome-support.php on line 439`

**Comment by evertiro** [comment]
Are the errors continuous, or just a few during the update timeframe? Plugins that depend upon Awesome Support don't always handle things well when the parent plugin is disabled during the update process. If they aren't continuous and didn't interfere with the upgrade, they're safe to ignore. I don't personally have the my-cred plugin, but I'm going to be submitting a patch for the plugins I do have access to, and hopefully it'll get added and carried over to the rest of them.

**Comment by Mohal** [comment]
This must have occurred during plug-in update. The file mentioned in the error is in the code.
