### ISSUE TITLE
Wrong function used

### ISSUE THREAD

**Issue by MansourJabin** [Awesome-Support/Awesome-Support#760]
Hi , Thank you for your good product .
in _awesome-support/includes/functions-post.php_ line 92 , it should be `$messages = $go->get_error_message();` instead of `$messages = $go->get_error_messages();` .
Because in _wpas_add_error()_ must pass string but passed array now;

**Comment by Mohal** [comment]
> 
> 
> Hi , Thank you for your good product .
> in _awesome-support/includes/functions-post.php_ line 92 , it should be `$messages = $go->get_error_message();` instead of `$messages = $go->get_error_messages();` .
> Because in _wpas_add_error()_ must pass string but passed array now;

Hi Mansour,

Thanks for pointing this out. Let me take a look into this.
