### ISSUE TITLE
Ticket links under the ID column is not constructing correctly

### ISSUE THREAD

**Issue by sharif-ah** [Awesome-Support/Awesome-Support#815]
In admin ticket listing, under the ID column, the URL/link is not generated correctly from the update of 6.0.13. 

Currently the invalid link generated: `https://example.com/wp-admin/post.php?post=12345&action=edit%20target=`

The correct ticket link should be: `https://example.com/wp-admin/post.php?post=12345&action=edit`

**Comment by sharif-ah** [comment]
Fix is requested for pull at https://github.com/Awesome-Support/Awesome-Support/pull/817

**Comment by Mohal** [comment]
Pull request merged
