### ISSUE TITLE
Fatal error:  Uncaught TypeError: strip_tags()

### ISSUE THREAD

**Issue by NasimNet** [Awesome-Support/Awesome-Support#818]
Hello

When we search in the admin section, the site encounters an error.
```
 PHP Fatal error:  Uncaught TypeError: strip_tags(): Argument #1 ($string) must be of type string, array given in ...\wp-includes\formatting.php:5374
```

To fix the problem, it is enough to make the following change.
```
File : includes\functions-templating.php
Function Name : wpas_show_taxonomy_column
Change : 
$get           = array_map('wp_strip_all_tags', (array) $_GET);
$get           = stripslashes_deep( (array) $_GET );
```

Thanks if this change is included in the new version.
Thanks for your great plugin

**Comment by Mohal** [comment]
@NasimNet can you please send us a Pull Request for this change?

**Comment by Mohal** [comment]
Pull request created for this issue. Closin' issue.
